### PR TITLE
Expose thread_info in specifications.

### LINKED ISSUE #165: Enable notation for specifications that depend on the thread_id
Some specifications depend on `thread_id`s, these should be supported.

### PR DESCRIPTION
**Pull request by gmalecha**
This closes #165, but does not yet address #164.

### CODE REVIEW

**Comment by gmalecha** [comment]
@jmgrosen If you could take a look at this and sanity check it when you get a few minutes.

**Comment by jmgrosen** [comment]
I think I misunderstood you on Friday -- I thought you wanted to be able to *instantiate* the `thread_info` type at certain places. You're instead planning to keep it abstract and add axioms for interacting with it, it looks like?

**Comment by jmgrosen** [comment]
I'll go ahead and merge this once CI passes.

**Comment by gmalecha** [comment]
We do need to instantiate `thread_info`, but that will be a different PR. I have to think more about how it will work most cleanly.

**Pull request merged**
